[project]
name = "cvbuilder"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dynamic = ["dependencies", "optional-dependencies"]

[project.scripts]
your-command = "main:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.package-data]
project_name_here = ["templates/*"]
